### PR TITLE
Made test compatible with ES 1.0.1

### PR DESCRIPTION
**Pull request by svenmeys**
Hey, we're using this at our company and just upgraded to ES 1.0.1. Since there were a few changes, this is a quick attempt to fix broken stuff and hope everything keeps working.

You'll see that multi_value fields have changed the most. It may not be pretty code (yet) but it works for now!

### CODE REVIEW

**Comment by vmassol** [comment]
I have the same problem... We're upgrading to ES 1.0.1 and our tests were using elasticsearch-test and we're now stuck since the matest elasticsearch-test works only with ES 0.90.6...

**Comment by vmassol** [comment]
Thanks a lot Sven for your patch it helped me a lot :)

**Comment by svenmeys** [comment]
YW,

Be careful if you use multi-fields. I have quick-fixed those annotations, but didn't really double check as we don't use that feature ourselves.

**Comment by dlobue** [comment]
My team is in the same boat. Waiting on this to get merged before we can upgrade to ES 1.0.1

**Comment by tlrx** [comment]
Great, thanks!

**Pull request merged**
